### ISSUE TITLE
Drag Container not working on Safari

### ISSUE THREAD

**Issue by noeliasfranco** [peterh32/react-drag-drop-container#11]
I created some components using DragDropContainer. So far, all was working great but it seems that is not working on any Safari version. Is the component compatible with Safari?

**Comment by benj3** [comment]
Also receiving this any updates?

**Comment by noeliasfranco** [comment]
No for now :( @benj3

**Comment by 1auralynn** [comment]
I was able to get it working https://github.com/peterh32/react-drag-drop-container/pull/12

Note that another issue is that draggable=false is not set on DOM elements automatically in Safari so it can look kind of wonky unless you manually set it.

**Comment by benj3** [comment]
Thank you @1auralynn !

**Comment by noeliasfranco** [comment]
@1auralynn so what I have to do is add draggable=false on the each DragDropContainer that I use?

**Comment by 1auralynn** [comment]
Is it not dragging at all?

**Comment by 1auralynn** [comment]
You should set draggable=false on any DOM children of your DragDropContainer, otherwise there is interference w/ the default DOM dragging behavior. You probably shouldn't set it on the container itself. Also, you rebuilt the module right? You can just grab the bundle.js from my commit and swap yours out.

**Comment by peterh32** [comment]
This should be fixed now, I hope! Fixed the draggable=false thing and took @1auralynn 's fix on figuring out the left mouse button.
